import { parseEnv } from "./parse-env"

export { parseEnv, type AppEnv, type Env, type PublicEnvInput } from "./parse-env"

export const env = parseEnv({
  EXPO_PUBLIC_APP_ENV: process.env.EXPO_PUBLIC_APP_ENV,
  EXPO_PUBLIC_API_URL: process.env.EXPO_PUBLIC_API_URL,
  EXPO_PUBLIC_GOOGLE_PLACES_ANDROID_API_KEY: process.env.EXPO_PUBLIC_GOOGLE_PLACES_ANDROID_API_KEY,
  EXPO_PUBLIC_GOOGLE_PLACES_IOS_API_KEY: process.env.EXPO_PUBLIC_GOOGLE_PLACES_IOS_API_KEY,
  EXPO_PUBLIC_GOOGLE_PLACES_WEB_API_KEY: process.env.EXPO_PUBLIC_GOOGLE_PLACES_WEB_API_KEY,
  EXPO_PUBLIC_GOOGLE_PLACES_ANDROID_SHA1: process.env.EXPO_PUBLIC_GOOGLE_PLACES_ANDROID_SHA1,
  EXPO_PUBLIC_ONESIGNAL_APP_ID: process.env.EXPO_PUBLIC_ONESIGNAL_APP_ID,
  EXPO_PUBLIC_CLOUDINARY_CLOUD_NAME: process.env.EXPO_PUBLIC_CLOUDINARY_CLOUD_NAME,
  EXPO_PUBLIC_CLOUDINARY_UPLOAD_PRESET: process.env.EXPO_PUBLIC_CLOUDINARY_UPLOAD_PRESET,
})
